name: Stage 2 — Staging Provision, Deploy, Test, Destroy

on:
  workflow_run:
    workflows: ["Stage 1 CI — Test, Build & Push to ACR"]
    types: [completed]
  workflow_dispatch:

env:
  LOCATION: australiaeast
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: latest

jobs:
  staging:
    name: Provision, Deploy to Staging, Test, Destroy
    runs-on: ubuntu-latest
    if: >
      ${{
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'testing'
      }} || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (SPN)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set names for resources
        id: names
        run: |
          echo "rg=week10-staging-rg-${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "plan=week10-staging-plan-${{ github.run_id }}" >> $GITHUB_OUTPUT
          echo "app=week10-staging-app-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Create Resource Group
        run: |
          az group create \
            --name "${{ steps.names.outputs.rg }}" \
            --location "${{ env.LOCATION }}"

      - name: Create App Service Plan (Linux, B1)
        run: |
          az appservice plan create \
            --name "${{ steps.names.outputs.plan }}" \
            --resource-group "${{ steps.names.outputs.rg }}" \
            --location "${{ env.LOCATION }}" \
            --is-linux \
            --sku B1

      - name: Create Staging WebApp from ACR
        run: |
          az webapp create \
            --resource-group "${{ steps.names.outputs.rg }}" \
            --plan "${{ steps.names.outputs.plan }}" \
            --name "${{ steps.names.outputs.app }}" \
            --deployment-container-image-name "${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }}"

      - name: Restart WebApp and warm up
        run: |
          az webapp restart \
            --resource-group "${{ steps.names.outputs.rg }}" \
            --name "${{ steps.names.outputs.app }}"
          sleep 20

      - name: Destroy staging environment (always)
        if: always()
        run: |
          az group delete \
            --name "${{ steps.names.outputs.rg }}" \
            --yes --no-wait
